version: '3.8'

services:
  backend:
    build:
      context: ./b_realtime_chat
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - realtime-chat-network
    restart: unless-stopped

  frontend:
    build:
      context: ./f_realtime_chat
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - realtime-chat-network
    restart: unless-stopped

networks:
  realtime-chat-network:
    driver: bridge